spring:
  datasource:
    url: jdbc:h2:mem:advice-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jwt:
    secret: "qqPe5S/7kiCllG/wsbwnVh+VUlU4V01zD5OI6gdEDke0zTLons1wSVpj7bd8yGi5"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080