spring:
  application:
    name: AdviceApi
  datasource:
    url: jdbc:h2:mem:advice-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-secret-key-should-be-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

swagger:
  enabled: true
  