spring:
  datasource:
    url: jdbc:h2:mem:advice-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: verySecretKeyChangeThis
  expiration-ms: 3600000

server:
  port: 8080