spring:
  datasource:
    url: jdbc:h2:mem:advice-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:ZmFrZV9zZWNyZXRfZm9yX2Rldl9vbmx5X3Rlc3Rpbmc=} # base64
    issuer: advice-api
    ttl-seconds: ${JWT_TTL_SECONDS:900}

  admin:
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:Admin@1234}

logging:
  level:
    org.springdoc: DEBUG
    io.swagger.v3: DEBUG

springdoc:
  override-with-generic-response: false